# List defaults
default:
    @just --list

GREEN  := "\\u001b[32m"
RESET  := "\\u001b[0m\\n"
CHECK  := "\\xE2\\x9C\\x94"

build:
    @yarn dev

up: build
    ./build

test:
    @echo  " {{CHECK}} No tests yet, so guess they pass? {{CHECK}}"
